# Gemfile
source "https://rubygems.org"

# 指定 Jekyll 版本
gem "jekyll", "~> 4.3.4"

gem "minimal-mistakes-jekyll"

# 插件區塊，包含 jekyll-feed 和 jekyll-remote-theme
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-remote-theme"  # 新增 jekyll-remote-theme 插件
end

# Windows 支援的插件
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# 提升 Windows 檔案監控效能
gem "wdm", "~> 0.1", platforms: [:mingw, :x64_mingw, :mswin]

# JRuby 的 http_parser.rb 插件
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]

